# Generated by Django 5.2.13 on 2026-04-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KmoocCourse',
            fields=[
                ('course_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='강좌 ID')),
                ('course_name', models.CharField(max_length=300, verbose_name='강좌명')),
                ('org_code', models.CharField(blank=True, max_length=100, verbose_name='기관 코드')),
                ('org_name', models.CharField(blank=True, max_length=200, verbose_name='기관명')),
                ('professor', models.CharField(blank=True, max_length=300, verbose_name='교수자')),
                ('course_image', models.URLField(blank=True, verbose_name='썸네일')),
                ('course_url', models.URLField(blank=True, verbose_name='강좌 URL')),
                ('summary', models.TextField(blank=True, verbose_name='강좌 소개')),
                ('enrollment_start', models.DateTimeField(blank=True, null=True, verbose_name='수강신청 시작')),
                ('enrollment_end', models.DateTimeField(blank=True, null=True, verbose_name='수강신청 종료')),
                ('study_start', models.DateTimeField(blank=True, null=True, verbose_name='학습 시작')),
                ('study_end', models.DateTimeField(blank=True, null=True, verbose_name='학습 종료')),
                ('public_yn', models.BooleanField(default=True, verbose_name='공개 여부')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 여부')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='동기화 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='최초 등록')),
            ],
            options={
                'verbose_name': 'K-MOOC 강좌',
                'verbose_name_plural': 'K-MOOC 강좌 목록',
                'ordering': ['-study_start'],
                'indexes': [models.Index(fields=['course_name'], name='kmooc_name_idx'), models.Index(fields=['is_active', 'public_yn'], name='kmooc_active_idx')],
            },
        ),
    ]
