# Generated by Django 5.2.13 on 2026-04-24 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalScoreSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_date', models.DateField()),
                ('capital_score', models.FloatField()),
                ('asset_stability', models.FloatField()),
                ('goal_progress', models.FloatField()),
                ('routine_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '캐피털 점수 스냅샷',
                'verbose_name_plural': '캐피털 점수 스냅샷 목록',
                'ordering': ['-score_date'],
                'unique_together': {('user', 'score_date')},
            },
        ),
    ]
