# Generated by Django 5.2.13 on 2026-04-25 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TodayAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('category', models.CharField(default='general', help_text='financial/housing/learning/routine/general', max_length=20)),
                ('completed', models.BooleanField(default=False)),
                ('action_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='today_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '오늘의 행동',
                'verbose_name_plural': '오늘의 행동 목록',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DailyKeyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('question_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '오늘의 핵심 질문',
                'verbose_name_plural': '오늘의 핵심 질문 목록',
                'ordering': ['-question_date'],
                'unique_together': {('user', 'question_date')},
            },
        ),
    ]
