# Generated by Django 5.2.13 on 2026-04-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='learning_interests',
            field=models.JSONField(blank=True, default=list, help_text="학습 관심사 태그 목록 (예: ['IT', '금융'])"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferred_region',
            field=models.CharField(blank=True, help_text='희망 지역 (예: 서울 성동구). 온보딩 시 입력.', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferred_region_code',
            field=models.CharField(blank=True, help_text='법정동 코드 5자리 (예: 11200). MOLIT API 조회용.', max_length=10),
        ),
    ]
