# Generated by Django 5.2.13 on 2026-04-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_learning_interests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='notify_daily_action',
            field=models.BooleanField(default=False, help_text='일일 행동 알림 수신 여부 (미구현 — UI 토글 설정값 저장용)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferred_ai_model',
            field=models.CharField(choices=[('auto', '자동 선택'), ('gemma', 'Gemma 4 E2B'), ('qwen', 'Qwen 2.5'), ('server', '서버 고성능')], default='auto', help_text='사용자가 선택한 AI 모델 (Settings 화면)', max_length=20),
        ),
    ]
