# Generated by Django 5.2.13 on 2026-05-04 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_code', models.CharField(max_length=30, unique=True)),
                ('sector_name_ko', models.CharField(max_length=50)),
                ('sector_name_en', models.CharField(max_length=50)),
                ('market', models.CharField(choices=[('KR', '한국'), ('US', '미국'), ('ALL', '공통')], max_length=5)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'TBL_MARKET_SECTOR',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='MarketCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20, unique=True)),
                ('company_name_ko', models.CharField(blank=True, max_length=100)),
                ('company_name_en', models.CharField(max_length=100)),
                ('market', models.CharField(choices=[('KR', '한국'), ('US', '미국')], max_length=5)),
                ('exchange', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.marketsector')),
            ],
            options={
                'db_table': 'TBL_MARKET_COMPANY',
            },
        ),
        migrations.CreateModel(
            name='NewsAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateField()),
                ('market', models.CharField(choices=[('KR', '한국'), ('US', '미국'), ('ALL', '전체')], max_length=5)),
                ('engine_type', models.CharField(choices=[('langgraph', 'LangGraph'), ('crewai', 'CrewAI')], default='langgraph', max_length=20)),
                ('run_status', models.CharField(choices=[('PENDING', '대기'), ('RUNNING', '실행 중'), ('COMPLETED', '완료'), ('FAILED', '실패')], default='PENDING', max_length=20)),
                ('overall_analysis', models.TextField(blank=True)),
                ('raw_result', models.JSONField(blank=True, null=True)),
                ('run_duration_ms', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'TBL_NEWS_ANALYSIS',
                'unique_together': {('analysis_date', 'market', 'engine_type')},
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_url', models.TextField(unique=True)),
                ('title', models.TextField()),
                ('content', models.TextField(blank=True)),
                ('source_name', models.CharField(blank=True, max_length=100)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('market', models.CharField(blank=True, choices=[('KR', '한국'), ('US', '미국')], max_length=5)),
                ('language', models.CharField(default='ko', max_length=5)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'TBL_NEWS_ARTICLE',
                'indexes': [models.Index(fields=['market'], name='TBL_NEWS_AR_market_5f8015_idx'), models.Index(fields=['-published_at'], name='TBL_NEWS_AR_publish_70f417_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserWatchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('watchlist_type', models.CharField(choices=[('SECTOR', '섹터'), ('COMPANY', '종목')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.marketcompany')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.marketsector')),
            ],
            options={
                'db_table': 'TBL_USER_WATCHLIST',
            },
        ),
        migrations.CreateModel(
            name='NewsSectorAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_text', models.TextField(blank=True)),
                ('article_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector_analyses', to='news.newsanalysis')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news.marketsector')),
            ],
            options={
                'db_table': 'TBL_NEWS_SECTOR_ANALYSIS',
                'unique_together': {('analysis', 'sector')},
            },
        ),
    ]
