# Generated by Django 5.2.13 on 2026-05-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_seed_sectors'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssectoranalysis',
            name='investment_signal',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 - 적극 매도'), (2, '2 - 비중 축소'), (3, '3 - 중립'), (4, '4 - 비중 확대'), (5, '5 - 적극 매수')], default=3, help_text='metric 보정 후 최종 시그널'),
        ),
        migrations.AddField(
            model_name='newssectoranalysis',
            name='investment_signal_raw',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 - 적극 매도'), (2, '2 - 비중 축소'), (3, '3 - 중립'), (4, '4 - 비중 확대'), (5, '5 - 적극 매수')], default=3, help_text='LLM 원본 시그널 (보정 전)'),
        ),
        migrations.AddField(
            model_name='newssectoranalysis',
            name='recommended_stocks',
            field=models.JSONField(default=list, help_text="[{'ticker': '005930', 'name': '삼성전자'}, ...] 마스터 매칭된 종목만 저장"),
        ),
    ]
