# Generated by Django 5.2.13 on 2026-04-24 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('capital_score', models.IntegerField(default=0)),
                ('goal_achievement_rate', models.FloatField(default=0.0)),
                ('journal_count', models.IntegerField(default=0)),
                ('action_completion_rate', models.FloatField(default=0.0)),
                ('highlights', models.JSONField(default=list)),
                ('improvements', models.JSONField(default=list)),
                ('next_week_action', models.CharField(blank=True, max_length=200)),
                ('ai_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '주간 복기 리포트',
                'verbose_name_plural': '주간 복기 리포트 목록',
                'ordering': ['-week_start'],
                'unique_together': {('user', 'week_start')},
            },
        ),
    ]
