# Generated by Django 5.2.13 on 2026-04-24 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('investment', 'investment'), ('housing', 'housing'), ('learning', 'learning'), ('routine', 'routine'), ('general', 'general')], max_length=15)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('ai_summary', models.TextField(blank=True)),
                ('action_items', models.JSONField(default=list)),
                ('mood_score', models.IntegerField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='goals.goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '의사결정 일지',
                'verbose_name_plural': '의사결정 일지 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
