# Generated by Django 5.2.13 on 2026-04-25 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('evidence_chips', models.JSONField(default=list)),
                ('scenarios', models.JSONField(default=list)),
                ('model_used', models.CharField(default='gemma4:e2b', max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('journal_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision_scenario', to='journal.journalentry')),
            ],
            options={
                'verbose_name': '의사결정 시나리오',
                'verbose_name_plural': '의사결정 시나리오 목록',
            },
        ),
    ]
