# Generated by Django 5.2.13 on 2026-04-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_decisionscenario'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='dart_corp_code',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='dart_corp_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
