# Generated by Django 5.2.13 on 2026-05-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_journalentry_dart_corp_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisionscenario',
            name='model_used',
            field=models.CharField(default='gemma4:latest', max_length=50),
        ),
    ]
